apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gcpstorageversioningconstraintv1
spec:
  crd:
    spec:
      names:
        kind: GCPStorageVersioningConstraintV1
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package gcpstorageversioningconstraintv1

      violation[{"msg": msg}] {
          bucketName := input.review.object.metadata.name
          bucketVersioning := input.review.object.spec.versioning.enabled
          bucketVersioning == false
          msg := sprintf("Cloud Storage bucket versioning is required: bucket name <%v>", [bucketName])
      }

      violation[{"msg": msg}] {
          not input.review.object.spec.versioning.enabled
          bucketName := input.review.object.metadata.name
          msg := sprintf("No versioning configuration provided: bucket name <%v>", [bucketName])
      }