apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GCPStorageVersioningConstraintV1
metadata:
  name: versioning-required
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - storage.cnrm.cloud.google.com
      kinds:
      - StorageBucket
    namespaces:
    - config-control